apiVersion: v1
kind: Service
metadata:
  name: corp-tower-server
  labels:
    app.kubernetes.io/name: corp-tower-server
    app.kubernetes.io/part-of: corp-tower
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: corp-tower-server
    app.kubernetes.io/part-of: corp-tower
  ports:
    - name: websocket
      port: 3000
      targetPort: websocket
      nodePort: 30300
