import { existsSync, lstatSync, readFileSync, readdirSync } from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';
import { extract } from '../build-file-map.mjs';

export const CONCEPT_INDEX_BEGIN = '<!-- BEGIN GENERATED CONCEPT ROUTER -->';
export const CONCEPT_INDEX_END = '<!-- END GENERATED CONCEPT ROUTER -->';
export const CONCEPT_MAP_MARKER = 'GENERATED by `scripts/build-concept-map.mjs` — do not hand-edit.';
export const DEFAULT_CONCEPT_BYTES = 12 * 1024;
export const MAX_CONCEPT_BYTES = 24 * 1024;
export const CONCEPT_SECTION_HARD_BYTES = 6 * 1024;
export const CONCEPT_MAX_LINE_CHARS = 400;

const ID = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$/;
const FIELDS = new Set(['id', 'alias', 'source', 'adjacent']);
const REPEATABLE = new Set(['alias', 'source', 'adjacent']);
const PROHIBITED_SOURCE_ROOTS = new Set([
  '.agent-state',
  'KB',
  'plan',
  'reference',
  'repair',
  'report',
  'task',
]);

const normalizePath = value => value.replaceAll('\\', '/').replace(/^(?:\.\/)+/, '');
const relativePath = (root, file) => relative(root, file).replaceAll('\\', '/');

export function normalizeConceptAlias(value) {
  return value.normalize('NFKC').trim().toLowerCase().replace(/\s+/g, ' ');
}

export function headingSlug(value) {
  return value.replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1').replaceAll('`', '')
    .trim().toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s/g, '-');
}

function inside(parent, child) {
  return child === parent || child.startsWith(parent + sep);
}

function problem(status, message, details = {}) {
  return { status, message, ...details };
}

function markdownHeadings(lines) {
  return lines.flatMap((line, index) => {
    const match = /^(#{1,6})\s+(.+)$/.exec(line);
    return match ? [{ line: index + 1, level: match[1].length, heading: match[2] }] : [];
  });
}

function sectionForHeading(lines, headings, heading, metadataStarts) {
  const next = headings.find(candidate => candidate.line > heading.line && candidate.level <= heading.level);
  const nextMetadata = metadataStarts.find(line => line > heading.line && (!next || line < next.line));
  const end = nextMetadata ? nextMetadata - 1 : next ? next.line - 1 : lines.length;
  return {
    start: heading.line,
    end,
    text: lines.slice(heading.line - 1, end).join('\n').trimEnd(),
  };
}

function parseMetadata(lines, start, end, path, errors) {
  const values = new Map();
  for (let index = start + 1; index < end; index++) {
    if (!lines[index].trim()) continue;
    const match = /^([a-z]+):\s*(.*?)\s*$/.exec(lines[index]);
    if (!match) {
      errors.push(problem('section-missing', `${path}:${index + 1} has malformed concept metadata`, { path, line: index + 1 }));
      continue;
    }
    const [, field, value] = match;
    if (!FIELDS.has(field)) {
      errors.push(problem('section-missing', `${path}:${index + 1} has unknown metadata field '${field}'`, { path, line: index + 1 }));
      continue;
    }
    if (!value) {
      errors.push(problem('section-missing', `${path}:${index + 1} has an empty '${field}' value`, { path, line: index + 1 }));
      continue;
    }
    if (!REPEATABLE.has(field) && values.has(field))
      errors.push(problem('section-duplicate', `${path}:${index + 1} repeats '${field}'`, { path, line: index + 1 }));
    if (!values.has(field)) values.set(field, []);
    values.get(field).push(value);
  }
  return values;
}

function sourceReference(value, concept, path, line, errors) {
  const split = value.lastIndexOf('#');
  if (split <= 0 || split === value.length - 1) {
    errors.push(problem('source-anchor-missing', `${path}:${line} source '${value}' must be repo/path#stable-anchor`, {
      path, line, concept_id: concept,
    }));
    return null;
  }
  const sourcePath = normalizePath(value.slice(0, split));
  const anchor = value.slice(split + 1).trim();
  if (!sourcePath || sourcePath.startsWith('/') || sourcePath.split('/').includes('..')) {
    errors.push(problem('access-denied', `${path}:${line} source '${value}' is not repository-relative`, {
      path, line, concept_id: concept,
    }));
    return null;
  }
  if (PROHIBITED_SOURCE_ROOTS.has(sourcePath.split('/')[0])) {
    errors.push(problem('access-denied', `${path}:${line} concept source enters prohibited root '${sourcePath.split('/')[0]}/'`, {
      path, line, concept_id: concept, source_path: sourcePath,
    }));
  }
  if (/^\d+$/.test(anchor) || /:\d+(?:-\d+)?$/.test(sourcePath)) {
    errors.push(problem('source-anchor-missing', `${path}:${line} authored metadata depends on a generated line number`, {
      path, line, concept_id: concept, source_path: sourcePath, anchor,
    }));
  }
  return { path: sourcePath, anchor, authored: value, metadata_line: line };
}

function conceptDocuments(kbRoot) {
  const contextRoot = join(kbRoot, 'docs/context');
  if (!existsSync(contextRoot)) return [];
  return readdirSync(contextRoot, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.md'))
    .map(entry => join(contextRoot, entry.name))
    .filter(file => !['CONCEPT-SCHEMA.md', 'index.md'].includes(basename(file)))
    .sort((left, right) => left.localeCompare(right));
}

export function loadConceptRegistry({ root = '.', kbRoot = 'KB' } = {}) {
  const repositoryRoot = resolve(root);
  const resolvedKbRoot = resolve(repositoryRoot, kbRoot);
  const errors = [];
  const concepts = [];

  if (!inside(repositoryRoot, resolvedKbRoot)) {
    return {
      root: repositoryRoot,
      kb_root: resolvedKbRoot,
      concepts,
      by_id: new Map(),
      aliases: new Map(),
      reverse_sources: new Map(),
      errors: [problem('access-denied', 'KB root must stay inside the repository')],
    };
  }

  for (const file of conceptDocuments(resolvedKbRoot)) {
    const ownerPath = relativePath(repositoryRoot, file);
    const lines = readFileSync(file, 'utf8').replace(/\r\n/g, '\n').split('\n');
    const headings = markdownHeadings(lines);
    const metadataStarts = lines.flatMap((line, index) => line.trim() === '<!-- kb' ? [index + 1] : []);
    const claimedHeadings = new Map();
    for (let index = 0; index < lines.length; index++) {
      if (lines[index].trim() !== '<!-- kb') continue;
      const end = lines.findIndex((line, candidate) => candidate > index && line.trim() === '-->');
      if (end < 0) {
        errors.push(problem('section-missing', `${ownerPath}:${index + 1} has an unterminated concept block`, {
          path: ownerPath, line: index + 1,
        }));
        break;
      }
      const values = parseMetadata(lines, index, end, ownerPath, errors);
      const heading = headings.find(candidate => candidate.line === end + 2);
      const id = values.get('id')?.[0] || '';
      if (!heading) {
        errors.push(problem('section-missing', `${ownerPath}:${index + 1} metadata must be followed immediately by one Markdown heading`, {
          path: ownerPath, line: index + 1, concept_id: id || null,
        }));
        index = end;
        continue;
      }
      if (claimedHeadings.has(heading.line)) {
        errors.push(problem('section-duplicate', `${ownerPath}:${heading.line} is owned by more than one metadata block`, {
          path: ownerPath, line: heading.line, concept_id: id || null,
        }));
      }
      claimedHeadings.set(heading.line, id);
      const nested = headings.find(candidate => candidate.line > heading.line && candidate.level > heading.level
        && !headings.some(boundary => boundary.line > heading.line && boundary.line < candidate.line && boundary.level <= heading.level));
      if (nested) {
        errors.push(problem('section-duplicate', `${ownerPath}:${heading.line} metadata owns a non-leaf heading with nested section '${nested.heading}'`, {
          path: ownerPath, line: heading.line, concept_id: id || null,
        }));
      }
      if (!id) {
        errors.push(problem('concept-unmapped', `${ownerPath}:${index + 1} concept metadata has no id`, {
          path: ownerPath, line: index + 1,
        }));
      } else if (!ID.test(id)) {
        errors.push(problem('concept-unmapped', `${ownerPath}:${index + 1} has invalid concept id '${id}'`, {
          path: ownerPath, line: index + 1, concept_id: id,
        }));
      }
      const section = sectionForHeading(lines, headings, heading, metadataStarts);
      const sourceLines = [];
      for (let metadataLine = index + 1; metadataLine < end; metadataLine++)
        if (lines[metadataLine].startsWith('source: ')) sourceLines.push(metadataLine + 1);
      const sources = (values.get('source') || []).map((value, sourceIndex) =>
        sourceReference(value, id, ownerPath, sourceLines[sourceIndex] || index + 1, errors)).filter(Boolean);
      concepts.push({
        id,
        domain: id.split('.')[0] || '',
        owner: {
          path: ownerPath,
          relative_path: relativePath(join(resolvedKbRoot, 'docs/context'), file),
          heading: heading.heading,
          level: heading.level,
          lines: [section.start, section.end],
          metadata_lines: [index + 1, end + 1],
        },
        section: section.text,
        aliases: [...new Set((values.get('alias') || []).map(value => value.trim()))],
        normalized_aliases: [...new Set((values.get('alias') || []).map(normalizeConceptAlias))],
        sources,
        adjacent: [...new Set((values.get('adjacent') || []).map(value => value.trim()))],
      });
      index = end;
    }
  }

  const byId = new Map();
  for (const concept of concepts) {
    if (!byId.has(concept.id)) byId.set(concept.id, []);
    byId.get(concept.id).push(concept);
  }
  for (const [id, matches] of byId) {
    if (id && matches.length > 1)
      errors.push(problem('section-duplicate', `concept id '${id}' owns ${matches.length} sections`, { concept_id: id }));
  }

  const aliases = new Map();
  for (const concept of concepts) {
    for (const alias of concept.normalized_aliases) {
      if (!aliases.has(alias)) aliases.set(alias, []);
      aliases.get(alias).push(concept);
    }
  }
  for (const [alias, matches] of aliases) {
    const ids = [...new Set(matches.map(concept => concept.id))];
    if (ids.length > 1)
      errors.push(problem('alias-ambiguous', `normalized alias '${alias}' resolves to ${ids.join(', ')}`, { alias, concept_ids: ids }));
    if (byId.has(alias) && !ids.includes(alias))
      errors.push(problem('alias-ambiguous', `normalized alias '${alias}' conflicts with a canonical concept id`, {
        alias, concept_ids: [alias, ...ids],
      }));
  }

  for (const concept of concepts) {
    for (const adjacent of concept.adjacent) {
      if (adjacent === concept.id)
        errors.push(problem('concept-unmapped', `concept '${concept.id}' cannot be adjacent to itself`, { concept_id: concept.id }));
      else if (!byId.has(adjacent))
        errors.push(problem('concept-unmapped', `concept '${concept.id}' has unknown adjacency '${adjacent}'`, {
          concept_id: concept.id, adjacent,
        }));
    }
  }

  const reverseSources = new Map();
  for (const concept of concepts) {
    for (const source of concept.sources) {
      if (!reverseSources.has(source.path)) reverseSources.set(source.path, []);
      reverseSources.get(source.path).push(concept.id);
    }
  }
  for (const [path, ids] of reverseSources) reverseSources.set(path, [...new Set(ids)].sort());

  return {
    root: repositoryRoot,
    kb_root: resolvedKbRoot,
    concepts: concepts.sort((left, right) => left.id.localeCompare(right.id)),
    by_id: byId,
    aliases,
    reverse_sources: reverseSources,
    errors,
  };
}

function stableTextMatches(lines, anchor) {
  const escaped = anchor.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const exactHeading = new RegExp(`^#{1,6}\\s+${escaped}\\s*$`, 'i');
  const exactKey = new RegExp(`^\\s*(?:["']?${escaped}["']?\\s*[:=]|\\[${escaped}\\])`);
  const word = new RegExp(`(^|[^A-Za-z0-9_%.-])${escaped}([^A-Za-z0-9_.-]|$)`);
  const preferred = lines.flatMap((line, index) => exactHeading.test(line) || exactKey.test(line) ? [index + 1] : []);
  if (preferred.length) return preferred;
  return lines.flatMap((line, index) => word.test(line) ? [index + 1] : []);
}

export function resolveConceptSource(root, source) {
  const repositoryRoot = resolve(root);
  const file = resolve(repositoryRoot, source.path);
  if (!inside(repositoryRoot, file) || PROHIBITED_SOURCE_ROOTS.has(source.path.split('/')[0]))
    return problem('access-denied', `source target '${source.path}' is outside the concept source grant`, { source });
  if (!existsSync(file) || !lstatSync(file).isFile())
    return problem('source-target-missing', `source target does not exist: ${source.path}`, { source });
  let text;
  try {
    text = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  } catch (error) {
    return problem('tool-error', `cannot read source target '${source.path}': ${error.message}`, { source });
  }
  const lines = text.split('\n');
  let matches = [];
  let kind = 'stable-text';
  if (source.anchor === '@file') {
    matches = [1];
    kind = 'file';
  } else {
    const symbols = extract(source.path, text).syms.filter(symbol => symbol.name === source.anchor);
    if (symbols.length) {
      matches = symbols.map(symbol => symbol.ln);
      kind = symbols[0].kind;
    } else {
      matches = stableTextMatches(lines, source.anchor);
    }
  }
  const unique = [...new Set(matches)];
  if (unique.length !== 1) {
    const reason = unique.length ? `source anchor '${source.anchor}' is ambiguous (${unique.length} matches) in ${source.path}`
      : `source anchor '${source.anchor}' is missing in ${source.path}`;
    return problem('source-anchor-missing', reason, { source, matches: unique });
  }
  const line = unique[0];
  const start = source.anchor === '@file' ? 1 : Math.max(1, line - 12);
  const end = Math.min(lines.length, source.anchor === '@file' ? 33 : line + 20);
  return {
    status: 'resolved',
    path: source.path,
    anchor: source.anchor,
    line,
    kind,
    file_lines: lines.length,
    read: {
      lines: [start, end],
      argv: ['sed', '-n', `${start},${end}p`, source.path],
      command: `sed -n ${start},${end}p ${source.path}`,
    },
  };
}

export function resolveRegistrySources(registry, { ready = false } = {}) {
  const errors = [...registry.errors];
  const concepts = registry.concepts.map(concept => {
    if (!concept.sources.length)
      errors.push(problem('concept-unmapped', `concept '${concept.id}' has no source grant`, { concept_id: concept.id }));
    const sources = concept.sources.map(source => resolveConceptSource(registry.root, source));
    for (const resolved of sources) {
      if (resolved.status !== 'resolved') errors.push({ ...resolved, concept_id: concept.id });
      else if (ready && resolved.anchor === '@file')
        errors.push(problem('source-anchor-missing', `concept '${concept.id}' retains unresolved migration seed '${resolved.path}#@file'`, {
          concept_id: concept.id, source_path: resolved.path, anchor: '@file',
        }));
    }
    return { ...concept, resolved_sources: sources };
  });
  return { ...registry, concepts, errors };
}

function escapeCell(value) {
  return String(value).replaceAll('|', '\\|').replace(/\s+/g, ' ').trim();
}

export function renderConceptMap(domain, concepts) {
  const lines = [
    `# Concept Map — ${domain}`,
    '',
    CONCEPT_MAP_MARKER,
    'Each row is derived from authored concept metadata and a current stable source anchor.',
    '',
  ];
  for (const concept of concepts) {
    lines.push(`## ${concept.id}`, '');
    lines.push(`Owner: \`${concept.owner.path}:${concept.owner.lines[0]}-${concept.owner.lines[1]}\` → **${concept.owner.heading}**`, '');
    lines.push('| Source | Anchor | Line | Bounded read |', '|---|---|---:|---|');
    for (const source of concept.resolved_sources) {
      if (source.status !== 'resolved') continue;
      lines.push(`| \`${escapeCell(source.path)}\` | \`${escapeCell(source.anchor)}\` | ${source.line} | \`${escapeCell(source.read.command)}\` |`);
    }
    lines.push('', `Adjacent concepts: ${concept.adjacent.length ? concept.adjacent.map(id => `\`${id}\``).join(', ') : 'none'}`, '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function renderConceptRouter(concepts) {
  const lines = [CONCEPT_INDEX_BEGIN];
  const domains = [...new Set(concepts.map(concept => concept.domain))].sort();
  for (const domain of domains) {
    lines.push('', `### ${domain}`, '', '| Concept | Owning section | Aliases |', '|---|---|---|');
    for (const concept of concepts.filter(item => item.domain === domain)) {
      const owner = concept.owner.relative_path;
      const link = `./${owner}#${headingSlug(concept.owner.heading)}`;
      lines.push(`| \`${concept.id}\` | [${escapeCell(owner)}#${escapeCell(headingSlug(concept.owner.heading))}](${link}) | ${escapeCell(concept.aliases.join(', '))} |`);
    }
  }
  lines.push('', CONCEPT_INDEX_END);
  return lines.join('\n');
}

export function expectedConceptOutputs(registry) {
  const resolved = resolveRegistrySources(registry, { ready: true });
  const outputs = new Map();
  const mapRoot = join(registry.kb_root, 'docs/context/map/concept');
  const domains = [...new Set(resolved.concepts.map(concept => concept.domain))].sort();
  for (const domain of domains) {
    const concepts = resolved.concepts.filter(concept => concept.domain === domain);
    outputs.set(join(mapRoot, `${domain}.md`), renderConceptMap(domain, concepts));
  }
  const indexFile = join(registry.kb_root, 'docs/context/index.md');
  if (!existsSync(indexFile)) {
    resolved.errors.push(problem('map-stale', `concept router index is missing: ${relativePath(registry.root, indexFile)}`));
  } else {
    const current = readFileSync(indexFile, 'utf8').replace(/\r\n/g, '\n');
    const begin = current.indexOf(CONCEPT_INDEX_BEGIN);
    const end = current.indexOf(CONCEPT_INDEX_END);
    if (begin < 0 || end < begin) {
      resolved.errors.push(problem('map-stale', `concept router markers are missing from ${relativePath(registry.root, indexFile)}`));
    } else {
      const before = current.slice(0, begin);
      const after = current.slice(end + CONCEPT_INDEX_END.length);
      outputs.set(indexFile, `${before}${renderConceptRouter(resolved.concepts)}${after}`);
    }
  }
  return { ...resolved, outputs };
}

export function conceptForInput(registry, input) {
  const requested = input.trim();
  const exact = registry.by_id.get(requested) || [];
  if (exact.length > 1)
    return problem('section-duplicate', `canonical concept id '${requested}' owns ${exact.length} sections`, { input });
  if (exact.length === 1) return { status: 'matched', concept: exact[0], resolution: 'id' };
  const alias = normalizeConceptAlias(requested);
  const matches = registry.aliases.get(alias) || [];
  const ids = [...new Set(matches.map(concept => concept.id))];
  if (ids.length > 1)
    return problem('alias-ambiguous', `exact normalized alias '${alias}' resolves to ${ids.join(', ')}`, { input, concept_ids: ids });
  if (matches.length === 1) return { status: 'matched', concept: matches[0], resolution: 'alias' };
  return problem('concept-unmapped', `no canonical concept id or exact normalized alias matches '${requested}'`, { input });
}

export function conceptMapPath(registry, concept) {
  return join(registry.kb_root, 'docs/context/map/concept', `${concept.domain}.md`);
}

export function readConceptMapSection(registry, concept) {
  const expectedConcept = {
    ...concept,
    resolved_sources: concept.sources.map(source => resolveConceptSource(registry.root, source)),
  };
  const expected = renderConceptMap(concept.domain, [expectedConcept]);
  const expectedLines = expected.split('\n');
  const expectedStart = expectedLines.findIndex(line => line === `## ${concept.id}`);
  const expectedSection = expectedLines.slice(expectedStart).join('\n').trimEnd();
  const file = conceptMapPath(registry, concept);
  const path = relativePath(registry.root, file);
  if (!existsSync(file)) return problem('map-stale', `concept map is missing: ${path}`, { path });
  const lines = readFileSync(file, 'utf8').replace(/\r\n/g, '\n').split('\n');
  const starts = lines.flatMap((line, index) => line === `## ${concept.id}` ? [index] : []);
  if (!starts.length) return problem('section-missing', `concept map section is missing for '${concept.id}'`, { path });
  if (starts.length > 1) return problem('section-duplicate', `concept map contains duplicate sections for '${concept.id}'`, { path });
  const start = starts[0];
  const next = lines.findIndex((line, index) => index > start && /^##\s+/.test(line));
  const end = next < 0 ? lines.length - 1 : next - 1;
  const text = lines.slice(start, next < 0 ? lines.length : next).join('\n').trimEnd();
  if (text !== expectedSection)
    return problem('map-stale', `concept map section is stale for '${concept.id}'`, { path, lines: [start + 1, end + 1] });
  return { status: 'matched', path, lines: [start + 1, end + 1], text };
}
