const GameConfig = {

    maxLevel: 99,
    debugStartLevel: 1,
    playersPerRoom: 3,
    placementCooldown: 1500,
    quickChatCooldownMs: 3000,
    quickChatTemplates: [
        "Place Block!",
        "Sorry!",
        "Hello!"
    ],
    targetHeightMultiplier: 3,
    targetHeightBase: 30,
    targetHeightStepBase: 10,
    targetHeightStepGrowth: 5,
    targetHeightStepGrowthEvery: 3,
    startDelayMs: 4000,
    lobbyReadyTimeoutMs: 60000,
    privateLobbyStartCountdownMs: 5000,
    privateLobbyReconnectPhaseMs: 10000,
    privateLobbyGracePhaseMs: 10000,
    levelTimeLimitMs: 120000,
    levelTimePlannedEfficiency: 0.55,
    levelTimeSlack: 3.0,
    levelTimeSlackMin: 1.5,
    levelTimeSlackFullLevel: 25,
    nextLevelDelayMs: 1000,
    failRestartDelayMs: 1000,
    placementScorePopupDurationMs: 5000,
    finishScorePopupDurationMs: 2000,
    levelSummaryDelayMs: 4000,
    impactInterval: 2,
    impactScoreRequirement: 0,
    impactMinContributionShare: 0.30,
    impactRecoverableFailures: 3,
    towerGridWidth: 8,
    placeableColumnMin: 2,
    placeableColumnMax: 5,
    towerSiteSlendernessTarget: 6.75,
    towerSiteWidthMin: 8,
    towerSiteWidthMax: 8,
    towerMaxTiltAngleDeg: 12,
    towerStructuralPoseMaxAngleDeg: 10,
    towerStructuralPoseMaxDipUnits: 0.18,
    towerStructuralPoseRigidRisk: 0.08,
    towerStructuralPoseIntegritySwayShare: 0.45,
    towerVisibleRowCapacity: 17,
    towerScrollStartRatio: 0.7,
    towerScrollEasePower: 3.0,
    towerTopIndicatorClearanceRows: 1,
    towerStabilityDifficulty: 30,
    towerLateralLoadShare: 0.45,
    towerStabilityPressure: {
        floor: 0.55,
        fullPressureLevel: 8,
        difficultyCurvePower: 2
    },
    towerSupportDifficultyPressure: {
        midpoint: 0.38,
        steepness: 8
    },
    towerStabilityAnchors: {
        forgiving: {
            towerBalanceSafeOffsetShare: 0.90,
            towerBalanceCollapseOffsetShare: 1.65,
            towerStructuralLoadExponent: 0.92,
            towerRedundancyBonus: 0.45,
            towerStructuralSeverity: 0.55,
            towerStabilityMinHeight: 10,
            towerHeightPressureGain: 0.0,
            towerSupportSafeLoadPerContact: 9.6,
            towerSupportCollapseLoadPerContact: 48
        },
        harsh: {
            towerBalanceSafeOffsetShare: 0.40,
            towerBalanceCollapseOffsetShare: 1.00,
            towerStructuralLoadExponent: 0.68,
            towerRedundancyBonus: 0.65,
            towerStructuralSeverity: 1.35,
            towerStabilityMinHeight: 8,
            towerHeightPressureGain: 1.3,
            towerSupportSafeLoadPerContact: 3.2,
            towerSupportCollapseLoadPerContact: 16
        }
    },
    towerBaseHalfWidthFloor: 1.0,
    towerStabilityWarningThreshold: 75,
    towerStabilityCriticalThreshold: 30,
    towerStabilityMoodThreshold: 2,
    towerStabilityFeedbackMode: process.env.CORP_TOWER_LIVE_PREVIEW_ENABLED === "false"
        ? "warnings_only"
        : "live_preview",
    powerUnlockLevel: 1,
    powerMaxSlots: 3,
    powerActivationCooldownMs: 3000,
    powerLastChanceEnabled: false,
    powerLifetime: "impact",
    powerGuaranteedBaseline: false,
    powerImpactMvpReward: false,
    powerReplenishPileShare: 0.25,
    powerCatalog: {
        score_cap: { category: "Offensive", title: "Score Cap", active: false },
        copy_score: { category: "Defensive", title: "Copy Score", active: false },
        refresh: { category: "Utility", title: "Refresh", active: false },
        replenish: { category: "Utility", title: "Replenish", active: true }
    },
    brickShapes: [
        { shapeId: "I", cells: [[0, 0], [0, 1], [0, 2], [0, 3]] },
        { shapeId: "O", cells: [[0, 0], [1, 0], [0, 1], [1, 1]] },
        { shapeId: "L", cells: [[0, 0], [1, 0], [0, 1], [0, 2]] },
        { shapeId: "T", cells: [[1, 0], [0, 1], [1, 1], [2, 1]] },
        { shapeId: "Z", cells: [[1, 0], [2, 0], [0, 1], [1, 1]] }
    ],
    brickWeights: {
        I: 1,
        O: 3,
        L: 2,
        T: 2,
        Z: 2
    },
    inventoryScaling: {
        1: 3
    },
    maxActiveBlocks: 3,
    maxTeamCarryOverBlocks: 3,
    maxGeneratedDrawPileBlocks: 4096,
    supplyEffectiveWidthRatio: 0.40,
    levelSupplyMinSurplus: 0,
    levelSupplyMaxSurplus: 4,
    levelSupplyMaxSurplusShare: 0.08,
    levelSupplyCoverageStart: 1.05,
    levelSupplyCoverageEnd: 0.75,
    levelSupplyCoverageFullLevel: 15,
    minPrecisionBlocksPerLevel: 3,
    openingHandGenerationAttempts: 1000,
    refreshGenerationAttempts: 100,
    refreshMinUsefulBlockHeight: 2,
    accessibility: {
        parallelPlacement: false
    },
    visualHooks: {
        impactBeat: true,
        screenShake: true,
        impactBeatMinZoom: 0.3,
        impactBeatZoomOutMs: 900,
        impactBeatWaveMs: 1100,
        impactBeatHoldMs: 0,
        collapseDebrisLifetimeMs: 1000,
        screenShakeMs: 460,
        screenShakeMagnitudeUnits: 0.22
    },
    scoring: {
        placementScorePerHeight: 10,
        recoveryHeightScorePercent: 50,
        strongReinforcementActionShare: 2.0,
        strongStructuralImprovement: 0.30,
        fullDangerRiskIncrease: 0.25,
        dangerousHeightFloor: 0.35,
        criticalSaveActionShare: 3.0,
        criticalSaveMinRiskReduction: 0.30,
        criticalSaveMinLoadShare: 0.30,
        criticalSaveMaxPerLevel: 2,
        finisherBonusPerLevel: 0,
        perfectBuildFinisherActionShare: 5.0,
        perfectBuildImpactRequirementShare: 0.15,
        assistBonusPerLevel: 0,
        assistContributionThreshold: 0.25
    },
    debugBotsEnabled: process.env.CORP_TOWER_BOTS_ENABLED === "true",
    showLatencyIndicator: process.env.CORP_TOWER_LATENCY_INDICATOR_ENABLED !== "false",
    debugBotCount: 2,
    debugBotDelayMin: 6000,
    debugBotDelayMax: 7000,
    debugBotStrategy: process.env.CORP_TOWER_BOT_STRATEGY === "cooperative"
        ? "mvp_greedy"
        : "cooperative",
    debugBotStabilityTolerance: 5,
    debugBotGapCandidates: 6,
};

module.exports = GameConfig;
