name: EKS Deploy All

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Which server(s) to deploy."
        required: true
        type: choice
        options:
          - All
          - Game only
          - Web only
        default: All

permissions:
  id-token: write
  contents: read

jobs:
  deploy-game:
    name: Deploy wstodplay
    if: ${{ inputs.deploy_target == 'All' || inputs.deploy_target == 'Game only' }}
    uses: ./.github/workflows/EKS-Deploy-Game-Server.yml
    with:
      target: wstodplay
    secrets: inherit

  deploy-web:
    name: Deploy todplay
    if: ${{ inputs.deploy_target == 'All' || inputs.deploy_target == 'Web only' }}
    uses: ./.github/workflows/EKS-Deploy-Web-Server.yml
    with:
      target: todplay
    secrets: inherit
