name: K3s Deploy wsplaytod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy wsplaytod
    uses: ./.github/workflows/K3s-Deploy-Game-Server.yml
    with:
      target: wsplaytod
    secrets: inherit
