name: K3s Deploy wstodtest

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy wstodtest
    uses: ./.github/workflows/K3s-Deploy-Game-Server.yml
    with:
      target: wstodtest
    secrets: inherit
