name: K3s Deploy playtod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy playtod
    uses: ./.github/workflows/K3s-Deploy-Web-Server.yml
    with:
      target: playtod
    secrets: inherit
