name: K3s Deploy todtest

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy todtest
    uses: ./.github/workflows/K3s-Deploy-Web-Server.yml
    with:
      target: todtest
    secrets: inherit
